Repository Yanabada/Yanabada_FE, pull requests merged in 2024-01, with the labels that each got.

#11 Design: 텍스트 인풋 제작
  src/components/input/Checkbox/index.tsx
  src/components/input/TextInput/index.tsx
  src/components/input/TextInput/styles.ts
  src/styles/globalStyles.ts
Labels: Design

#12 Design : 하단+상단 네비바 제작
  .eslintrc.cjs
  custom.d.ts
  package-lock.json
  package.json
  src/assets/icons/nav_All.svg
  src/assets/icons/nav_Chat.svg
  src/assets/icons/nav_Home.svg
  src/assets/icons/nav_My.svg
  src/assets/icons/nav_Product.svg
  src/components/navBar/bottomNavBar/NavButton.tsx
  src/components/navBar/bottomNavBar/index.tsx
  src/components/navBar/bottomNavBar/styles.ts
  src/components/navBar/upperNavBar/index.tsx
  src/components/navBar/upperNavBar/styles.ts
  src/components/numberBadge/index.tsx
  src/components/numberBadge/styles.ts
  src/main.css
  src/pages/chat/apis/.gitkeep
  src/pages/chat/constants/.gitkeep
  src/pages/chat/hooks/.gitkeep
  src/pages/chat/index.tsx
  src/pages/chat/stores/.gitkeep
  src/pages/chat/styles/.gitkeep
  src/pages/chat/tests/.gitkeep
  src/pages/chat/types/.gitkeep
  src/pages/chat/utils/.gitkeep
  src/routes/router.tsx
  src/stores/AlertCountStore.ts
  src/styles/globalStyles.ts
  src/themes/theme.ts
  src/types/emotion.d.ts
  tsconfig.json
  vite.config.ts
Labels: Feat, Design

#13 Design: 공통 컴포넌트 - 카드 제작
  src/assets/map.svg
  src/components/.gitkeep
  src/components/card/ColumnCard/index.tsx
  src/components/card/ColumnCard/styles.ts
  src/components/card/RecentlyRowCard/index.tsx
  src/components/card/RecentlyRowCard/styles.ts
  src/components/card/RowCard/index.tsx
  src/components/card/RowCard/styles.ts
  src/components/card/RowCard/types.ts
  src/components/card/card.styles.ts
  src/pages/home/index.tsx
  tsconfig.json
Labels: Design

#15 Design: 공통컴포넌트 - 달력 제작
  package-lock.json
  package.json
  src/components/calendar/index.tsx
  src/components/calendar/styles.css
  src/pages/sell/apis/.gitkeep
  src/pages/sell/constants/.gitkeep
  src/pages/sell/hooks/.gitkeep
  src/pages/sell/index.tsx
  src/pages/sell/stores/.gitkeep
  src/pages/sell/styles/.gitkeep
  src/pages/sell/tests/.gitkeep
  src/pages/sell/types/.gitkeep
  src/pages/sell/utils/.gitkeep
Labels: Feat, Design

#16 Design: 공통컴포넌트 - 버튼 제작
  package-lock.json
  src/components/buttons/AuthenticationButton/index.tsx
  src/components/buttons/AuthenticationButton/styles.ts
  src/components/buttons/BaseButton/index.tsx
  src/components/buttons/BaseButton/styles.ts
  src/components/buttons/CardSectionButton/index.tsx
  src/components/buttons/CardSectionButton/styles.ts
  src/components/buttons/ColoredButtonForm/index.tsx
  src/components/buttons/ColoredButtonForm/styles.ts
  src/components/buttons/DateChangeButton/index.tsx
  src/components/buttons/DateChangeButton/styles.ts
  src/components/buttons/ListButton/index.tsx
  src/components/buttons/ListButton/styles.ts
  src/components/buttons/TextButton/index.tsx
  src/components/buttons/TextButton/styles.ts
  src/components/buttons/ToggleButton/index.tsx
  src/components/buttons/ToggleButton/styles.ts
Labels: Fix, Design

#21 Design: 홈 헤더 & 검색 디자인
  src/assets/icons/nav_Logo.svg
  src/assets/icons/yanolja_Icon.svg
  src/pages/home/components/Header/index.tsx
  src/pages/home/components/Header/style.ts
  src/pages/home/components/SearchInput/index.tsx
  src/pages/home/components/SearchInput/style.ts
  src/pages/home/index.tsx
  src/routes/router.tsx
Labels: Design

#20 Feat: 푸터 디자인 및 배너 구현 (카테고리는 추후 디자인 예정)
  package-lock.json
  package.json
  src/assets/mountain.jpg
  src/assets/sea.jpg
  src/assets/underwater.jpg
  src/pages/home/components/Banner/images.ts
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Banner/styles.ts
  src/pages/home/components/Footer/index.tsx
  src/pages/home/components/Footer/styles.ts
  src/pages/home/components/Footer/tags.ts
Labels: Feat, Design

#29 Design: 공통 컴포넌트 체크박스 제작
  src/assets/icons/checkbox_Check.svg
  src/assets/icons/checkbox_rightArrow.svg
  src/components/input/Checkbox/AllConsentCheckbox.tsx
  src/components/input/Checkbox/IndividualConsentCheckbox.tsx
  src/components/input/Checkbox/allConsentCheckbox.style.ts
  src/components/input/Checkbox/index.tsx
  src/components/input/Checkbox/individualConsentCheckbox.style.ts
Labels: Feat, Design

#32 Feat: 체크박스 배경, 폰트 조절 props 추가
  src/components/input/Checkbox/AllConsentCheckbox.tsx
  src/components/input/Checkbox/allConsentCheckbox.style.ts
  src/components/input/Checkbox/index.tsx
Labels: Refactor, Design

#30 Feat: 카카오 지도 연결 및 검색 페이지 탭 제작
  index.html
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/apis/instance.ts
  src/assets/icons/resetIcon.svg
  src/assets/icons/search_Calendar.svg
  src/assets/icons/search_Person.svg
  src/assets/icons/search_Search.svg
  src/assets/icons/search_arrowDown.svg
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/components/BottomActions/styles.ts
  src/pages/search/components/SearchTab/index.tsx
  src/pages/search/components/SearchTab/styles.ts
  src/pages/search/index.tsx
  src/routes/router.tsx
  src/styles/base.ts
  tsconfig.json
Labels: Feat, Design

#33 Design: 전체 상품 리스트 화면 구현
  package-lock.json
  package.json
  src/assets/icons/Star.svg
  src/components/navBar/bottomNavBar/NavButton.tsx
  src/components/navBar/bottomNavBar/index.tsx
  src/components/navBar/upperNavBar/styles.ts
  src/pages/products/components/CategoryTab/index.tsx
  src/pages/products/components/CategoryTab/style.ts
  src/pages/products/components/Items/index.tsx
  src/pages/products/components/Items/style.ts
  src/pages/products/components/OptionTap/index.tsx
  src/pages/products/components/OptionTap/style.ts
  src/pages/products/components/Order/ToggleMenu.tsx
  src/pages/products/components/Order/index.tsx
  src/pages/products/components/Order/style.ts
  src/pages/products/components/SearchBar/index.tsx
  src/pages/products/components/SearchBar/style.ts
  src/pages/products/index.tsx
  src/pages/products/styles/style.ts
  src/routes/router.tsx
  src/themes/theme.ts
Labels: Design

#38 Feat: 공통 컴포넌트 가격 모달 및 가격 인풋 구현
  package-lock.json
  src/assets/icons/QuestionIcon.svg
  src/assets/noitems-logo.png
  src/components/notice/index.tsx
  src/components/notice/styles.ts
  src/components/priceArea/index.tsx
  src/components/priceArea/styles.ts
  src/components/priceModal/index.tsx
  src/components/priceModal/styles.ts
  src/constants/feePolicys.ts
  src/pages/sell/detail.tsx
  src/pages/sell/index.tsx
  src/pages/sell/register.tsx
  src/pages/sell/styles/detail.ts
  src/pages/sell/styles/register.ts
  src/pages/sell/styles/styles.ts
  src/utils/checkDayOfFee.ts
  src/utils/getDayOfWeek.ts
  src/utils/numberFormat.ts
Labels: Feat, Design

#36 Feat: 게스트 숫자 관리 컴포넌트 제작
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/pages/search/components/SearchTab/GuestCounter.tsx
  src/pages/search/components/SearchTab/SearchNotice.tsx
  src/pages/search/components/SearchTab/guestCounter.style.ts
  src/pages/search/components/SearchTab/searchNotice.style.ts
  src/pages/search/index.tsx
  src/pages/search/store/guestStore.ts
  src/styles/globalStyles.ts
Labels: Feat, Design

#43 Design: 마이페이지(G-4) 화면구현
  src/animations/dropDown.ts
  src/assets/icons/informationIcon.svg
  src/assets/icons/noPointIcon.svg
  src/components/buttons/CardSectionButton/index.tsx
  src/components/chips/DiscountChip/index.tsx
  src/components/navBar/bottomNavBar/NavButton.tsx
  src/components/navBar/bottomNavBar/index.tsx
  src/components/navBar/upperNavBar/styles.ts
  src/pages/myPage/components/PointsMiddleTabDisappear/index.tsx
  src/pages/myPage/components/PointsMiddleTabList/index.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/points.tsx
  src/pages/myPage/profile.tsx
  src/pages/myPage/styles/points.styles.ts
  src/pages/myPage/styles/pointsMiddleTab.styles.ts
  src/pages/products/components/Order/ToggleMenu.tsx
  src/pages/products/components/Order/index.tsx
  src/routes/router.tsx
  src/styles/globalStyles.ts
  tsconfig.json
Labels: Design

#44 Design: 로그인 & 회원가입 페이지 화면 구현
  src/assets/icons/caution_Icon.svg
  src/assets/icons/logo_yanabada_gradient.svg
  src/assets/icons/logo_yanolja_gray.svg
  src/assets/icons/question_Icon.svg
  src/components/buttons/ColoredButtonForm/index.tsx
  src/components/buttons/ColoredButtonForm/styles.ts
  src/components/input/Checkbox/AllConsentCheckbox.tsx
  src/components/input/Checkbox/IndividualConsentCheckbox.tsx
  src/components/input/Checkbox/index.tsx
  src/components/input/Checkbox/individualConsentCheckbox.style.ts
  src/components/input/TextInput/index.tsx
  src/components/navBar/upperNavBar/index.tsx
  src/components/notice/index.tsx
  src/components/notice/styles.ts
  src/pages/login/EmailLogin.tsx
  src/pages/login/apis/.gitkeep
  src/pages/login/components/signInBottomSheet/SignInBottomSheet.tsx
  src/pages/login/components/signInBottomSheet/signInBottomSheet.styles.ts
  src/pages/login/constants/.gitkeep
  src/pages/login/hooks/.gitkeep
  src/pages/login/index.tsx
  src/pages/login/stores/.gitkeep
  src/pages/login/styles/.gitkeep
  src/pages/login/styles/emailLogin.styles.ts
  src/pages/login/styles/login.styles.ts
  src/pages/login/tests/.gitkeep
  src/pages/login/types/.gitkeep
  src/pages/login/utils/.gitkeep
  src/pages/products/components/Order/index.tsx
  src/pages/signIn/apis/.gitkeep
  src/pages/signIn/components/signInFirst/SignInFirst.tsx
  src/pages/signIn/components/signInFirst/signInFirst.styles.ts
  src/pages/signIn/components/signInSecond/SignInSecond.tsx
  src/pages/signIn/components/signInSecond/signInSecond.styles.ts
  src/pages/signIn/components/signInThird/SignInThird.tsx
  src/pages/signIn/components/signInThird/signInThird.styles.ts
  src/pages/signIn/constants/.gitkeep
  src/pages/signIn/hooks/.gitkeep
  src/pages/signIn/index.tsx
  src/pages/signIn/stores/.gitkeep
  src/pages/signIn/styles/styles.ts
  src/pages/signIn/tests/.gitkeep
  src/pages/signIn/types/.gitkeep
  src/pages/signIn/utils/.gitkeep
  src/routes/router.tsx
Labels: Fix, Design

#42 Feat: 지도 관련 기능 추가 (내 위치, 숙소 리스트 가격 마커 등) & 검색 페이지 숙소 카드 디자인 수정
  src/assets/icons/airplane.svg
  src/assets/icons/mapIcon.svg
  src/assets/icons/myPosition.svg
  src/main.css
  src/pages/products/components/Items/index.tsx
  src/pages/products/components/KakaoMap/EventMarkerContainer.tsx
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/KakaoMap/styles.ts
  src/pages/products/components/ProductCard/ProductCardForMap.tsx
  src/pages/products/components/ProductCard/index.tsx
  src/pages/products/components/ProductCard/style.ts
  src/pages/products/components/SearchBar/style.ts
  src/pages/products/components/ToMapButton/index.tsx
  src/pages/products/components/ToMapButton/styles.ts
  src/pages/products/index.tsx
  src/pages/products/styles/style.ts
  src/pages/products/types/index.ts
  src/routes/router.tsx
Labels: Feat, Refactor, Design

#48 Design: 마이페이지(G-5) 화면구현
  src/assets/icons/dottedLineIcon.svg
  src/assets/icons/infoIcon.svg
  src/assets/icons/timerIcon.svg
  src/components/badges/index.tsx
  src/components/badges/styles.ts
  src/components/buttons/AuthenticationButton/index.tsx
  src/components/buttons/BaseButton/index.tsx
  src/components/buttons/BaseButton/styles.ts
  src/components/buttons/CardSectionButton/index.tsx
  src/components/buttons/CardSectionButton/styles.ts
  src/components/buttons/FloatingButton/index.tsx
  src/components/buttons/ToggleButton/index.tsx
  src/components/card/ListCard/index.tsx
  src/components/card/ListCard/styles.ts
  src/components/chips/AdditionalServiceChip/index.tsx
  src/components/chips/InfoChip/index.tsx
  src/components/chips/ManipulationChip/index.tsx
  src/components/modal/index.tsx
  src/components/notice/index.tsx
  src/pages/login/EmailLogin.tsx
  src/pages/login/components/signInBottomSheet/SignInBottomSheet.tsx
  src/pages/login/index.tsx
  src/pages/myPage/components/Info/index.tsx
  src/pages/myPage/components/Info/styles.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/salesHistory.tsx
  src/pages/myPage/styles/salesHistory.styles.ts
  src/pages/myPage/styles/transactionStatement.styles.ts
  src/pages/myPage/transactionStatement.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/signIn/components/signInFirst/SignInFirst.tsx
  src/pages/signIn/components/signInThird/SignInThird.tsx
  src/routes/router.tsx
Labels: Design

#52 Design: 마이페이지(G-6) 화면구현
  src/components/card/ListCard/index.tsx
  src/pages/myPage/components/Info/index.tsx
  src/pages/myPage/components/Info/styles.ts
  src/pages/myPage/components/TransactionStatementNotice/index.tsx
  src/pages/myPage/components/TransactionStatementNotice/styles.ts
  src/pages/myPage/purchaseHistory.tsx
  src/pages/myPage/salesHistory.tsx
  src/pages/myPage/styles/history.styles.ts
  src/pages/myPage/transactionStatement.tsx
  src/routes/router.tsx
Labels: Refactor, Design

#49 Feat: 전체 상품 리스트 msw 연결
  package.json
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/products/api/products.ts
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/Order/style.ts
  src/pages/products/components/ProductCard/ProductCardForMap.tsx
  src/pages/products/components/ProductCard/index.tsx
  src/pages/products/components/ProductCard/style.ts
  src/pages/products/index.tsx
  src/pages/products/styles/style.ts
  src/pages/products/types/productsType.ts
  src/pages/search/styles/style.ts
  src/routes/router.tsx
  tsconfig.json
Labels: Feat

#50 Design: 양도 페이지 화면 구현
  src/components/buttons/AuthenticationButton/index.tsx
  src/components/buttons/DateChangeButton/index.tsx
  src/components/buttons/DateChangeButton/styles.ts
  src/components/calendar/styles.css
  src/components/notice/index.tsx
  src/components/notice/styles.ts
  src/components/priceArea/index.tsx
  src/components/priceArea/styles.ts
  src/pages/sell/detail.tsx
  src/pages/sell/index.tsx
  src/pages/sell/register.tsx
  src/pages/sell/styles/detail.ts
  src/pages/sell/styles/register.ts
  src/pages/sell/styles/styles.ts
  src/routes/router.tsx
  src/styles/globalStyles.ts
  src/utils/numberFormat.ts
Labels: Design

#54 Feat: 지도 마커 클러스터러 추가 & msw 연동
  index.html
  package.json
  src/mocks/api/data/products.ts
  src/mocks/handlers.ts
  src/pages/products/api/products.ts
  src/pages/products/api/queries.ts
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/ProductCard/ProductCardForMap.tsx
  src/pages/products/components/ProductCard/style.ts
  src/pages/products/index.tsx
Labels: Feat, Refactor, Design

#56 Feat: 상품 상세 페이지 디자인 및 리액트 쿼리 생성
  src/assets/icons/copy.svg
  src/assets/icons/small_line_check.svg
  src/assets/icons/yanabada_ci.svg
  src/components/buttons/BaseButton/index.tsx
  src/components/buttons/BaseButton/styles.ts
  src/components/say/index.tsx
  src/components/say/style.ts
  src/mocks/handlers.ts
  src/pages/productDetail/api/detail.ts
  src/pages/productDetail/components/DetailInfo/index.tsx
  src/pages/productDetail/components/DetailInfo/style.ts
  src/pages/productDetail/components/DetailNotice/index.tsx
  src/pages/productDetail/components/DetailNotice/style.ts
  src/pages/productDetail/components/Footer/index.tsx
  src/pages/productDetail/components/Footer/style.ts
  src/pages/productDetail/components/Information/index.tsx
  src/pages/productDetail/components/Information/style.ts
  src/pages/productDetail/components/Location/index.tsx
  src/pages/productDetail/components/Location/style.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/productDetail/components/NegoButton/style.ts
  src/pages/productDetail/components/SellerSay/index.tsx
  src/pages/productDetail/components/SellerSay/style.ts
  src/pages/productDetail/components/ServiceInfo/index.tsx
  src/pages/productDetail/components/ServiceInfo/style.ts
  src/pages/productDetail/hooks/useProductDetail.ts
  src/pages/productDetail/index.tsx
  src/pages/productDetail/styles/style.ts
  src/pages/productDetail/types/detailType.ts
  src/routes/router.tsx
Labels: Feat, Design

#59 Design: 양도 확인페이지 2p
  src/components/buttons/DateChangeButton/index.tsx
  src/components/buttons/DateChangeButton/styles.ts
  src/components/navBar/upperNavBar/index.tsx
  src/components/priceArea/styles.ts
  src/pages/sell/components/InfoBox.tsx
  src/pages/sell/confirm.tsx
  src/pages/sell/detail.tsx
  src/pages/sell/result.tsx
  src/pages/sell/styles/confirm.ts
  src/pages/sell/styles/register.ts
  src/pages/sell/styles/result.ts
  src/routes/router.tsx
Labels: Design

#64 Design: 홈페이지 ~높은 할인율 상품 디자인
  src/assets/icons/nav_Logo.svg
  src/components/card/RecentlyRowCard/styles.ts
  src/components/card/RowCard/index.tsx
  src/components/card/card.styles.ts
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Banner/styles.ts
  src/pages/home/components/CategoryProduct/index.tsx
  src/pages/home/components/CategoryProduct/style.ts
  src/pages/home/components/Header/index.tsx
  src/pages/home/components/Header/style.ts
  src/pages/home/components/RecentlyProduct/index.tsx
  src/pages/home/components/RecentlyProduct/style.ts
  src/pages/home/components/SearchInput/style.ts
  src/pages/home/index.tsx
  src/pages/home/styles/style.ts
  src/routes/router.tsx
Labels: Design

#66 Feat: PWA 알림 기능을 위한 FCM 연동
  .gitignore
  package.json
  public/firebase-messaging-sw.js
  src/components/buttons/ListButton/index.tsx
  src/firebase-messaging-sw.js
  src/main.tsx
  src/pages/myPage/index.tsx
  src/utils/.gitkeep
  tsconfig.json
Labels: Feat, Env, Chore

#68 Design: 홈 화면 디자인 특별 상품 ~ 푸터
  src/assets/icons/arrowRight.svg
  src/components/card/ColumnCard/index.tsx
  src/components/chips/ManipulationChip/index.tsx
  src/components/chips/ManipulationChip/styles.ts
  src/main.css
  src/mocks/api/data/products.ts
  src/mocks/handlers.ts
  src/pages/home/components/CategoryList/index.tsx
  src/pages/home/components/CategoryList/styles.ts
  src/pages/home/components/Footer/index.tsx
  src/pages/home/components/Footer/styles.ts
  src/pages/home/components/SearchInput/style.ts
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/home/components/SpecialServices/styles.ts
  src/pages/home/components/SubServices/index.tsx
  src/pages/home/components/SubServices/styles.ts
  src/pages/home/index.tsx
  src/pages/products/api/products.ts
  src/pages/products/api/queries.ts
  src/pages/products/types/productsType.ts
  src/styles/base.ts
Labels: Feat, Design

#72 Design: 구매페이지(H-1) 화면구현
  src/assets/icons/profileIcon_gray.svg
  src/assets/icons/tossIcon.svg
  src/components/buttons/ToggleButton/index.tsx
  src/components/input/TextInput/index.tsx
  src/components/notice/index.tsx
  src/components/notice/styles.ts
  src/pages/myPage/components/Info/styles.ts
  src/pages/myPage/purchaseHistory.tsx
  src/pages/products/components/ProductCard/style.ts
  src/pages/purchase/index.tsx
  src/pages/purchase/styles/.gitkeep
  src/pages/purchase/styles/styles.ts
  src/routes/router.tsx
Labels: Refactor, Design

#76 Design: 구매페이지(H-2) 화면구현
  src/components/certification/index.tsx
  src/components/certification/styles.ts
  src/pages/purchase/certification.tsx
  src/pages/purchase/editInfo.tsx
  src/routes/router.tsx
Labels: Design

#80 Feat: 숙소 전체 리스트 쿼리 전체적인 수정 & 홈 알림 페이지 디자인
  src/assets/icons/bin.svg
  src/assets/icons/product_position_mark.svg
  src/components/card/ColumnCard/index.tsx
  src/mocks/api/data/products.ts
  src/mocks/handlers.ts
  src/pages/home/components/Header/index.tsx
  src/pages/home/components/SearchInput/style.ts
  src/pages/home/components/SpecialServices/styles.ts
  src/pages/home/components/SubServices/index.tsx
  src/pages/notice/index.tsx
  src/pages/notice/styles.ts
  src/pages/productDetail/components/Location/index.tsx
  src/pages/products/api/products.ts
  src/pages/products/api/queries.ts
  src/pages/products/components/KakaoMap/MyPositionMarker.tsx
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/KakaoMap/styles.ts
  src/pages/products/components/ProductCard/index.tsx
  src/pages/products/components/ToMapButton/index.tsx
  src/pages/products/components/ToMapButton/styles.ts
  src/pages/products/index.tsx
  src/pages/products/types/productsType.ts
  src/routes/router.tsx
  src/utils/formatDateTo.ts
Labels: Feat, Design

#79 Feat: 상품 리스트 카테고리 url params 설정
  src/pages/home/components/CategoryProduct/style.ts
  src/pages/home/components/Header/index.tsx
  src/pages/home/components/Header/style.ts
  src/pages/home/components/RecentlyProduct/style.ts
  src/pages/home/index.tsx
  src/pages/products/components/CategoryTab/index.tsx
  src/pages/products/components/CategoryTab/style.ts
  src/pages/products/components/OptionTap/index.tsx
  src/pages/products/components/OptionTap/style.ts
  src/pages/products/components/Order/index.tsx
  src/pages/products/components/Order/style.ts
  src/pages/products/components/ProductCard/index.tsx
  src/pages/products/components/ProductCard/style.ts
  src/pages/products/stores/checkStore.ts
Labels: Feat

#85 Design: 구매 페이지 H-6 디자인
  src/assets/icons/payment_confirm.svg
  src/pages/purchase/reservationComplete.style.ts
  src/pages/purchase/reservationComplete.tsx
  src/routes/router.tsx
Labels: Design

#86 Feat: 회원가입/로그인 유효성 검사 추가
  .eslintrc.cjs
  package.json
  src/components/buttons/ColoredButtonForm/index.tsx
  src/components/buttons/ColoredButtonForm/styles.ts
  src/components/certification/index.tsx
  src/components/certification/styles.ts
  src/components/checkEmail/index.tsx
  src/components/checkEmail/styles.ts
  src/components/input/TextInput/styles.ts
  src/components/modal/styles.ts
  src/components/navBar/upperNavBar/index.tsx
  src/firebase-messaging-sw.js
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/chat/components/chatRoomBanner/styles.ts
  src/pages/login/EmailLogin.tsx
  src/pages/login/styles/emailLogin.styles.ts
  src/pages/purchase/editInfo.tsx
  src/pages/signIn/components/signInFirst/SignInFirst.tsx
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/pages/signIn/components/signInSecond/SignInSecond.tsx
  src/pages/signIn/components/signInThird/SignInThird.tsx
  src/pages/signIn/styles/styles.ts
  src/routes/router.tsx
Labels: Feat, Design

#91 Design: 구매페이지 예외케이스 디자인
  src/assets/icons/cautionIconRed.svg
  src/components/notice/index.tsx
  src/components/notice/styles.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/styles/styles.ts
  src/pages/purchase/index.tsx
  src/pages/purchase/styles/styles.ts
Labels: Design

#89 Feat: 알림 페이지 애니메이션 및 모달 추가
  .gitignore
  src/pages/notice/constants.ts
  src/pages/notice/index.tsx
  src/pages/notice/styles.ts
  src/pages/notice/type.ts
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/index.tsx
Labels: Feat, Design

#84 Feat: 야놀자페이 비밀번호 로직 & 양도페이지 날짜 선택에 따른 계산로직 구현
  .eslintrc.cjs
  src/components/buttons/DateChangeButton/index.tsx
  src/components/calendar/index.tsx
  src/components/priceArea/index.tsx
  src/constants/feePolicys.ts
  src/pages/charge/account.tsx
  src/pages/charge/components/Keypads/index.tsx
  src/pages/charge/components/Keypads/styles.ts
  src/pages/charge/index.tsx
  src/pages/charge/list.tsx
  src/pages/charge/password.tsx
  src/pages/charge/styles/list.ts
  src/pages/charge/styles/password.ts
  src/pages/charge/styles/styles.ts
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/sell/components/AutoCancelOption.tsx
  src/pages/sell/components/DateOption.tsx
  src/pages/sell/components/NegoOption.tsx
  src/pages/sell/confirm.tsx
  src/pages/sell/register.tsx
  src/pages/sell/result.tsx
  src/pages/sell/utils/calcEndFee.ts
  src/routes/router.tsx
  src/utils/dateFormat.ts
  src/utils/todayFormat.ts
Labels: Feat, Design

#94 Feat: 이미지 자동 슬라이드 및 세부 기능 구현
  src/mocks/handlers.ts
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Header/index.tsx
  src/pages/productDetail/components/DetailInfo/index.tsx
  src/pages/productDetail/components/DetailInfo/style.ts
  src/pages/productDetail/components/Footer/index.tsx
  src/pages/productDetail/components/Location/index.tsx
  src/pages/productDetail/components/NegoButton/style.ts
Labels: Feat

#101 Refactor: 검색 페이지 리팩토링 & 게스트 숫자 search params으로 관리
  src/components/calendar/index.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/index.tsx
  src/pages/search/components/CalendarTab.tsx
  src/pages/search/components/GuestCounterTab.tsx
  src/pages/search/components/KeywordTab.tsx
  src/pages/search/components/SearchTab/GuestCounter.tsx
  src/pages/search/components/SearchTab/SearchNotice.tsx
  src/pages/search/components/SearchTab/guestCounter.style.ts
  src/pages/search/components/SearchTab/searchNotice.style.ts
  src/pages/search/components/SearchTab/styles.ts
  src/pages/search/index.tsx
  src/pages/search/stores/tabStore.ts
  src/utils/formatDateTo.ts
Labels: Feat, Refactor

#104 Feat: 마이페이지, 구매페이지 유효성 검사 로직 추가
  src/apis/instance.ts
  src/assets/icons/cancelIcon.svg
  src/components/buttons/AuthenticationButton/styles.ts
  src/components/buttons/CardSectionButton/index.tsx
  src/components/certification/index.tsx
  src/components/chips/ManipulationChip/styles.ts
  src/components/input/TextInput/styles.ts
  src/pages/myPage/profile.tsx
  src/pages/myPage/styles/profile.styles.ts
  src/pages/purchase/index.tsx
  src/pages/purchase/styles/styles.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
Labels: Feat

#107 Feat: 일반 로그인 + accessToken 만료 시 refresh
  package.json
  src/apis/instance.ts
  src/pages/login/EmailLogin.tsx
  src/pages/login/index.tsx
  src/pages/login/styles/login.styles.ts
  src/utils/getCookie.ts
Labels: Feat

#106 Feat: 검색 페이지 로직 수정
  src/components/calendar/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/components/CalendarTab.tsx
  src/pages/search/components/GuestCounterTab.tsx
  src/pages/search/components/KeywordTab.tsx
  src/pages/search/components/SearchHistory/index.tsx
  src/pages/search/components/SearchHistory/style.ts
  src/pages/search/components/SearchTab/Keyword.tsx
  src/pages/search/constants/keyword.ts
  src/pages/search/index.tsx
  src/pages/search/stores/KeywordStore.ts
  src/pages/search/stores/historyStore.ts
  src/pages/search/styles/style.ts
  src/pages/search/types/history.ts
  src/stores/CalendarStore.ts
Labels: Feat

#108 Feat: 숙소 리스트 API 연동 (검색 가능)
  src/main.tsx
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/home/components/SubServices/index.tsx
  src/pages/home/index.tsx
  src/pages/products/api/products.ts
  src/pages/products/api/queries.ts
  src/pages/products/components/CategoryTab/index.tsx
  src/pages/products/components/KakaoMap/Research.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/KakaoMap/styles.ts
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/hooks/useIntersect.ts
  src/pages/products/hooks/useResearch.ts
  src/pages/products/index.tsx
  src/pages/products/stores/mapStore.ts
  src/pages/products/styles/style.ts
Labels: Feat, Refactor

#111 Feat: 홈 알림 API 연결
  src/apis/instance.ts
  src/pages/notice/api.ts
  src/pages/notice/index.tsx
  src/pages/notice/queries.ts
  src/pages/products/api/products.ts
Labels: Feat

#115 Feat: 홈 헤더 - 검색 수정
  src/assets/banner1.jpg
  src/assets/banner2.png
  src/assets/banner3.png
  src/assets/mountain.jpg
  src/assets/sea.jpg
  src/assets/underwater.jpg
  src/pages/home/api/accumulate.ts
  src/pages/home/components/Banner/images.ts
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Banner/styles.ts
  src/pages/home/components/SearchInput/index.tsx
  src/pages/home/components/SearchInput/style.ts
  src/pages/home/hooks/useAccumulate.ts
Labels: Feat

#112 Feat: 회원가입 & 닉네임 중복 조회 & useForm 동작 수정
  src/components/buttons/AuthenticationButton/index.tsx
  src/components/certification/index.tsx
  src/components/checkEmail/index.tsx
  src/components/checkNickname/index.tsx
  src/components/checkPassword/index.tsx
  src/pages/login/EmailLogin.tsx
  src/pages/purchase/index.tsx
  src/pages/signIn/apis/.gitkeep
  src/pages/signIn/apis/compareNicknameApi.ts
  src/pages/signIn/apis/signInApi.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/pages/signIn/stores/.gitkeep
  src/pages/signIn/stores/SignInDataStore.ts
Labels: Feat

#121 Feat: 마이페이지 MSW 연동
  src/components/buttons/CardSectionButton/index.tsx
  src/components/buttons/CardSectionButton/styles.ts
  src/components/card/ListCard/index.tsx
  src/components/checkEmail/index.tsx
  src/components/checkPassword/index.tsx
  src/firebase-messaging-sw.js
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/myPage/apis/.gitkeep
  src/pages/myPage/apis/deleteProduct.ts
  src/pages/myPage/apis/deleteTradeHistory.ts
  src/pages/myPage/apis/getBalance.ts
  src/pages/myPage/apis/getManagement.ts
  src/pages/myPage/apis/getProfileDetail.ts
  src/pages/myPage/apis/getPurchaseHistory.ts
  src/pages/myPage/apis/getPurchaseTransactionHistory.ts
  src/pages/myPage/apis/getSalesHistory.ts
  src/pages/myPage/apis/getSellTransactionHistory.ts
  src/pages/myPage/apis/postApprovalDeny.ts
  src/pages/myPage/apis/postLogout.ts
  src/pages/myPage/apis/postPurchaseCancel.ts
  src/pages/myPage/apis/postSaleApprove.ts
  src/pages/myPage/apis/putChangeNickname.ts
  src/pages/myPage/components/Info/index.tsx
  src/pages/myPage/hooks/.gitkeep
  src/pages/myPage/hooks/useApporvalDeny.ts
  src/pages/myPage/hooks/useBalance.ts
  src/pages/myPage/hooks/useChangeNickName.ts
  src/pages/myPage/hooks/useLogout.ts
  src/pages/myPage/hooks/useManagement.ts
  src/pages/myPage/hooks/useProducts.ts
  src/pages/myPage/hooks/useProfileDetail.ts
  src/pages/myPage/hooks/usePurchaseCancel.ts
  src/pages/myPage/hooks/usePurchaseHistory.ts
  src/pages/myPage/hooks/usePurchaseTransactionHistory.ts
  src/pages/myPage/hooks/useSaleApprove.ts
  src/pages/myPage/hooks/useSalesHistory.ts
  src/pages/myPage/hooks/useSellTransactionHistory.ts
  src/pages/myPage/hooks/useTradeHistory.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/management.tsx
  src/pages/myPage/profile.tsx
  src/pages/myPage/purchaseHistory.tsx
  src/pages/myPage/salesHistory.tsx
  src/pages/myPage/transactionStatement.tsx
  src/pages/myPage/utils/.gitkeep
  src/pages/myPage/utils/calculateDiscountRate.ts
  src/pages/myPage/utils/formatDate.ts
  src/pages/myPage/utils/formatNumberWithCommas.ts
  src/pages/myPage/utils/formatPhoneNumber.ts
  src/pages/myPage/utils/formatTimeUntilSaleEnd.ts
  src/pages/signIn/apis/postEmailAuth.ts
  src/pages/signIn/apis/putChangePassword.ts
  src/pages/signIn/apis/putPhoneNumber.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/pages/signIn/hooks/.gitkeep
  src/pages/signIn/hooks/useChangePassword.ts
  src/pages/signIn/hooks/useEmailAuth.ts
  src/pages/signIn/hooks/usePhoneNumber.ts
Labels: Feat

#122 Feat: 숙소 상세 페이지 API 연결 및 후기 컴포넌트 생성
  src/pages/productDetail/api/detail.ts
  src/pages/productDetail/components/DetailInfo/index.tsx
  src/pages/productDetail/components/Location/style.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/productDetail/components/Review/index.tsx
  src/pages/productDetail/components/Review/style.ts
  src/pages/productDetail/constants/review.ts
  src/pages/productDetail/hooks/useProductDetail.ts
  src/pages/productDetail/index.tsx
  src/pages/products/components/ProductCard/style.ts
  src/routes/router.tsx
Labels: Feat

#126 Fix: 마이페이지 실제 API 연동
  .eslintrc.cjs
  src/components/card/ListCard/index.tsx
  src/components/certification/index.tsx
  src/pages/myPage/apis/deleteProduct.ts
  src/pages/myPage/apis/deleteTradeHistory.ts
  src/pages/myPage/apis/getBalance.ts
  src/pages/myPage/apis/getManagement.ts
  src/pages/myPage/apis/getProfileDetail.ts
  src/pages/myPage/apis/getPurchaseHistory.ts
  src/pages/myPage/apis/getPurchaseTransactionHistory.ts
  src/pages/myPage/apis/getSalesHistory.ts
  src/pages/myPage/apis/getSellTransactionHistory.ts
  src/pages/myPage/apis/postApprovalDeny.ts
  src/pages/myPage/apis/postLogout.ts
  src/pages/myPage/apis/postPurchaseCancel.ts
  src/pages/myPage/apis/postSaleApprove.ts
  src/pages/myPage/apis/putChangeNickname.ts
  src/pages/myPage/hooks/useChangeNickName.ts
  src/pages/myPage/hooks/usePurchaseHistory.ts
  src/pages/myPage/hooks/useSalesHistory.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/profile.tsx
  src/pages/myPage/purchaseHistory.tsx
  src/pages/myPage/salesHistory.tsx
  src/pages/signIn/apis/postEmailAuth.ts
  src/pages/signIn/apis/putChangePassword.ts
  src/pages/signIn/apis/putPhoneNumber.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/routes/router.tsx
Labels: Feat

#124 Feat: 야놀자 페이 충전 API 연결
  src/components/priceArea/index.tsx
  src/pages/charge/apis/charge.ts
  src/pages/charge/confirm.tsx
  src/pages/charge/hooks/usePaymentDetail.ts
  src/pages/charge/hooks/usePaymentHistory.ts
  src/pages/charge/index.tsx
  src/pages/charge/password.tsx
  src/pages/charge/stores/amountStore.ts
  src/pages/charge/types/charge.ts
  src/pages/search/constants/keyword.ts
  src/routes/router.tsx
Labels: Feat

#132 Fix: API 주소 수정
  src/pages/home/api/accumulate.ts
  src/pages/products/api/products.ts
Labels: Fix

#133 Fix: accumulate api 헤더 제거
  src/pages/home/api/accumulate.ts
Labels: Fix

#130 Fix: 숙소 없을 때 지도 재검색 시 에러 해결
  src/assets/icons/no_products_icon.svg
  src/components/card/ColumnCard/index.tsx
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/products/components/KakaoMap/MyPositionMarker.tsx
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/Research.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/NoProduct/index.tsx
  src/pages/products/components/NoProduct/styles.ts
  src/pages/products/components/ProductCard/ProductCardForMap.tsx
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/index.tsx
  src/pages/products/stores/mapStore.ts
Labels: Fix

#138 Design: 홈 아이콘 및 배너 추가
  src/assets/icons/arrowRight.svg
  src/assets/icons/camping.svg
  src/assets/icons/guest_house.svg
  src/assets/icons/hot_place_2024.svg
  src/assets/icons/hotel.svg
  src/assets/icons/pension.svg
  src/assets/icons/pool_villa.svg
  src/components/card/card.styles.ts
  src/components/navBar/bottomNavBar/styles.ts
  src/pages/home/components/CategoryList/index.tsx
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/home/components/SpecialServices/styles.ts
Labels: Design

#117 Feat: 채팅 목록 및 메시지 API 연결
  package.json
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/apis/api.ts
  src/pages/chat/components/chatInput/index.tsx
  src/pages/chat/components/chatList/index.tsx
  src/pages/chat/components/chatText/index.tsx
  src/pages/chat/components/chatText/styles.ts
  src/pages/chat/hooks/publishApi.ts
  src/pages/chat/hooks/subscribeApi.ts
  src/pages/chat/hooks/useChatRooms.ts
  src/pages/chat/hooks/useDeleteRoom.ts
  src/pages/chat/hooks/useMessages.ts
  src/pages/chat/hooks/useSocket.ts
  src/pages/chat/hooks/useUpdateChatRoom.ts
  src/pages/chat/index.tsx
  src/pages/chat/types/chatRoom.ts
  src/pages/productDetail/api/detail.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  vite.config.ts
Labels: Feat, Refactor

#131 Feat: 페이가입 api 연결 및 양도 수정 페이지 보완
  src/components/buttons/BaseButton/index.tsx
  src/components/buttons/BaseButton/styles.ts
  src/components/card/ListCard/index.tsx
  src/components/priceTable/index.tsx
  src/pages/charge/account.tsx
  src/pages/charge/hooks/useRegisterPayment.ts
  src/pages/charge/intro.tsx
  src/pages/charge/password.tsx
  src/pages/charge/stores/passwordStore.ts
  src/pages/charge/success.tsx
  src/pages/charge/types/charge.ts
  src/pages/sell/apis/callSellApi.ts
  src/pages/sell/apis/patchSellData.ts
  src/pages/sell/components/AutoCancelOption.tsx
  src/pages/sell/confirm.tsx
  src/pages/sell/correct.tsx
  src/pages/sell/hooks/usePatchSellApi.ts
  src/pages/sell/hooks/useSellApi.ts
  src/pages/sell/register.tsx
  src/pages/sell/result.tsx
  src/pages/sell/styles/confirm.ts
  src/pages/sell/styles/register.ts
  src/pages/sell/styles/styles.ts
  src/routes/router.tsx
Labels: Feat

#135 Feat: 검색 & 상세 페이지 세부 사항 구현
  src/components/calendar/index.tsx
  src/components/card/RowCard/index.tsx
  src/components/card/RowCard/styles.ts
  src/components/card/card.styles.ts
  src/pages/home/components/CategoryProduct/index.tsx
  src/pages/home/index.tsx
  src/pages/productDetail/components/Location/index.tsx
  src/pages/productDetail/components/Location/style.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/productDetail/components/SellerSay/index.tsx
  src/pages/productDetail/index.tsx
  src/pages/productDetail/styles/style.ts
  src/pages/products/components/OptionTap/style.ts
  src/pages/products/components/SearchBar/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/index.tsx
Labels: Feat

#137 Feat: 구매 페이지 API 연동
  index.html
  src/apis/instance.ts
  src/components/buttons/AuthenticationButton/styles.ts
  src/components/buttons/CardSectionButton/index.tsx
  src/components/buttons/ToggleButton/index.tsx
  src/components/buttons/ToggleButton/styles.ts
  src/components/card/ListCard/index.tsx
  src/components/input/TextInput/index.tsx
  src/pages/myPage/apis/getProfileDetail.ts
  src/pages/myPage/components/Info/index.tsx
  src/pages/myPage/hooks/useBalance.ts
  src/pages/myPage/hooks/useProfileDetail.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/purchaseHistory.tsx
  src/pages/myPage/transactionStatement.tsx
  src/pages/myPage/utils/calculateDiscountRate.ts
  src/pages/myPage/utils/formatNumberWithCommas.ts
  src/pages/purchase/apis/.gitkeep
  src/pages/purchase/apis/postBuyProduct.ts
  src/pages/purchase/hooks/.gitkeep
  src/pages/purchase/hooks/useBuyProduct.ts
  src/pages/purchase/index.tsx
  src/pages/purchase/reservationComplete.tsx
  src/pages/purchase/types/.gitkeep
  src/pages/purchase/types/reservationData.ts
  src/pages/purchase/utils/.gitkeep
  src/pages/purchase/utils/convertString.ts
  src/pages/purchase/utils/formatDate.ts
  src/pages/purchase/utils/onClickPayment.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/routes/router.tsx
Labels: Feat

#152 Feat: FCM 토큰 업데이트 API 연동
  src/apis/instance.ts
  src/firebase-messaging-sw.ts
  src/main.tsx
  src/pages/home/api/putFCMToken.ts
  src/pages/home/hooks/useFCMToken.ts
  src/pages/home/index.tsx
  src/pages/myPage/apis/postLogout.ts
  src/pages/myPage/apis/putChangeNickname.ts
  src/pages/myPage/utils/formatNumberWithCommas.ts
  src/pages/signIn/apis/putChangePassword.ts
  src/pages/signIn/apis/putPhoneNumber.ts
  tsconfig.json
Labels: Feat

#153 Feat: 범식님 디자인 요구사항 반영
  src/pages/home/components/Header/style.ts
  src/pages/home/components/SearchInput/style.ts
Labels: Design

#155 Fix: img import 경로 수정 및 버튼 활성화 추가
  src/pages/charge/account.tsx
  src/pages/charge/confirm.tsx
  src/pages/charge/index.tsx
  src/pages/charge/intro.tsx
  src/pages/charge/list.tsx
  src/pages/charge/success.tsx
  src/pages/purchase/index.tsx
  src/pages/sell/index.tsx
Labels: Fix

#156 Fix: 채팅 관련 데이터 경로 수정
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/chatText/index.tsx
  src/pages/chat/hooks/useChatRooms.ts
  src/pages/chat/hooks/useSocket.ts
  src/pages/chat/index.tsx
  src/pages/productDetail/components/NegoButton/index.tsx
Labels: Fix

#159 Feat: 알림 없을 때 보여줄 페이지 제작
  src/pages/notice/components/NoNotice.tsx
  src/pages/notice/components/styles.ts
  src/pages/notice/index.tsx
Labels: Design

#163 Feat: 채팅방 배너 데이터 연결
  package.json
  public/apple-touch-icon-180x180.png
  public/assets/apple-touch-icon-180x180.png
  public/assets/cat.png
  public/assets/favicon-16x16.png
  public/assets/favicon.ico
  public/assets/favicon.png
  public/assets/maskable-icon-512x512.png
  public/assets/pwa-192x192.png
  public/assets/pwa-512x512.png
  public/assets/pwa-64x64.png
  public/cat.png
  public/favicon-16x16.png
  public/favicon.ico
  public/favicon.png
  public/maskable-icon-512x512.png
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/pwa-64x64.png
  src/components/bottomSheet/styles.ts
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/chat/components/chatText/index.tsx
  src/pages/chat/index.tsx
  src/pages/myPage/apis/postLogout.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/utils/formatTimeUntilSaleEnd.ts
  src/pages/productDetail/api/detail.ts
  src/pages/productDetail/types/detailType.ts
  src/utils/formatDateTo.ts
Labels: Feat

#166 Fix: 마이페이지, 구매페이지 2차 QA
  src/assets/icons/approvalIcon.svg
  src/assets/icons/guideIcon.svg
  src/assets/icons/infoCenterIcon.svg
  src/assets/icons/logoutIcon.svg
  src/assets/icons/purchaseIcon.svg
  src/assets/icons/salesIcon.svg
  src/assets/icons/termIcon.svg
  src/assets/icons/withdrawIcon.svg
  src/components/buttons/CardSectionButton/index.tsx
  src/components/buttons/ListButton/index.tsx
  src/components/card/ListCard/index.tsx
  src/components/numberBadge/index.tsx
  src/pages/myPage/hooks/useLogout.ts
  src/pages/myPage/hooks/useManagement.ts
  src/pages/myPage/index.tsx
  src/pages/purchase/index.tsx
  src/pages/purchase/reservationComplete.tsx
  src/pages/purchase/utils/onClickPayment.ts
  tsconfig.json
Labels: Fix

#168 Feat: 페이내역 무한스크롤 및 에러메세지 모달 띄우기
  src/pages/charge/account.tsx
  src/pages/charge/apis/charge.ts
  src/pages/charge/apis/register.ts
  src/pages/charge/hooks/usePaymentList.ts
  src/pages/charge/hooks/usePaymentQuery.ts
  src/pages/charge/hooks/useRegisterPayment.ts
  src/pages/charge/index.tsx
  src/pages/charge/intro.tsx
  src/pages/charge/list.tsx
  src/pages/charge/styles/list.ts
  src/pages/charge/success.tsx
  src/pages/sell/index.tsx
  src/pages/sell/types/sellListData.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
Labels: Feat

#171 Fix: 마이페이지, 구매페이지 3차 QA
  src/apis/instance.ts
  src/pages/myPage/apis/getSellTransactionHistory.ts
  src/pages/myPage/index.tsx
  src/pages/purchase/index.tsx
Labels: Fix

#173 Feat: 소셜로그인 테스트 및 채팅 데이터 누락 수정
  src/assets/successSignIn.svg
  src/components/bottomSheet/styles.ts
  src/components/certification/index.tsx
  src/components/checkNickname/index.tsx
  src/components/numberBadge/index.tsx
  src/pages/chat/components/chatList/index.tsx
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/signIn/apis/signInApi.ts
  src/pages/signIn/components/signInFourth/SignInFourth.tsx
  src/pages/signIn/components/signInThird/SignInThird.tsx
  src/pages/signIn/stores/SignInDataStore.ts
Labels: Feat

#176 Fix: 카카오 소셜로그인 링크 수정
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/login/index.tsx
Labels: Fix

#174 Fix: 검색 필터 체크인 체크아웃 추가 & 알림 삭제 시 refetch
  src/components/buttons/CardSectionButton/index.tsx
  src/main.tsx
  src/pages/myPage/hooks/useBalance.ts
  src/pages/myPage/hooks/useProfileDetail.ts
  src/pages/myPage/index.tsx
  src/pages/notice/components/styles.ts
  src/pages/notice/index.tsx
  src/pages/notice/queries.ts
  src/pages/products/api/products.ts
  src/pages/products/components/ProductList/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/stores/guestStore.ts
  src/pages/sell/apis/getSellList.ts
  src/pages/sell/hooks/useGetSellList.ts
  src/pages/sell/index.tsx
  src/styles/globalStyles.ts
Labels: Fix

#184 Fix: 지도, 검색, 홈 QA 수정
  src/components/card/ColumnCard/index.tsx
  src/pages/home/components/CategoryProduct/index.tsx
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/home/components/SubServices/index.tsx
  src/pages/home/components/SubServices/styles.ts
  src/pages/products/api/products.ts
  src/pages/products/api/queries.ts
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/Research.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/KakaoMap/styles.ts
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/hooks/usePreviousParams.ts
  src/pages/search/components/BottomActions/index.tsx
  src/utils/formatDateTo.ts
Labels: Fix

#183 Fix: 양도 QA 1차 수정
  src/components/priceArea/index.tsx
  src/components/priceTable/index.tsx
  src/components/say/index.tsx
  src/pages/charge/index.tsx
  src/pages/charge/success.tsx
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/productDetail/types/detailType.ts
  src/pages/sell/components/DateOption.tsx
  src/pages/sell/confirm.tsx
  src/pages/sell/constants/initialConfirmData.ts
  src/pages/sell/correct.tsx
  src/pages/sell/hooks/useSellApi.ts
  src/pages/sell/index.tsx
  src/pages/sell/register.tsx
  src/pages/sell/stores/endDateStore.ts
  src/pages/sell/styles/register.ts
  src/pages/sell/utils/calcEndFee.ts
  src/pages/sell/utils/getPercentage.ts
  src/routes/router.tsx
  src/utils/calcCancelFee.ts
  src/utils/checkDayOfFee.ts
Labels: Fix, Feat

#185 [Feat]: instance.ts 수정 및 이메일 인증 로직 변경
  src/apis/instance.ts
  src/components/checkEmail/index.tsx
  src/pages/myPage/index.tsx
  src/pages/signIn/apis/postCode.ts
  src/pages/signIn/apis/postEmailAuth.ts
  src/pages/signIn/apis/postEmailDuplicateCheck.ts
  src/pages/signIn/hooks/useCodeCheck.ts
  src/pages/signIn/hooks/useEmailAuth.ts
  src/pages/signIn/hooks/useEmailDuplicateCheck.ts
Labels: Feat

#188 Fix: 상품 상세 로그인 분기 처리 및 세부 디자인 조정
  src/components/input/TextInput/styles.ts
  src/pages/productDetail/components/DetailInfo/index.tsx
  src/pages/productDetail/components/DetailInfo/style.ts
  src/pages/productDetail/components/NegoButton/index.tsx
Labels: Fix

#190 Fix: 마이페이지, 구매페이지 5차 QA
  src/components/card/ListCard/index.tsx
  src/components/card/ListCard/styles.ts
  src/components/input/Checkbox/AllConsentCheckbox.tsx
  src/firebase-messaging-sw.ts
  src/pages/home/index.tsx
  src/pages/myPage/components/Info/index.tsx
  src/pages/myPage/profile.tsx
  src/pages/myPage/styles/history.styles.ts
  src/pages/myPage/styles/profile.styles.ts
  src/pages/notice/queries.ts
  src/pages/purchase/index.tsx
  src/pages/purchase/styles/styles.ts
  src/routes/router.tsx
  src/utils/indexDB.ts
Labels: Fix

#191 Fix: 1차 QA 반영 (홈, 검색, 상품리스트, 상세페이지)
  src/assets/icons/no_products_icon.svg
  src/components/card/RowCard/index.tsx
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Banner/styles.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/products/components/NoProduct/index.tsx
  src/pages/products/components/NoProduct/styles.ts
  src/pages/products/components/ProductCard/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/components/SearchHistory/index.tsx
  src/pages/search/components/SearchHistory/style.ts
  src/pages/search/index.tsx
Labels: Fix

#197 Fix: 양도/페이 3차 QA 수정
  src/components/priceArea/index.tsx
  src/pages/charge/apis/charge.ts
  src/pages/charge/index.tsx
  src/pages/charge/list.tsx
  src/pages/myPage/salesHistory.tsx
  src/pages/sell/components/AutoCancelOption.tsx
  src/pages/sell/confirm.tsx
  src/pages/sell/correct.tsx
  src/pages/sell/register.tsx
  src/utils/calcCancelFee.ts
Labels: Fix

#200 Feat: 채팅 기능 추가 구현
  src/components/navBar/bottomNavBar/NavButton.tsx
  src/components/navBar/bottomNavBar/index.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/apis/api.ts
  src/pages/chat/components/chatRoomBanner/index.tsx
  src/pages/chat/components/chatText/index.tsx
  src/pages/chat/components/noChatList/styles.ts
  src/pages/chat/hooks/.gitkeep
  src/pages/chat/hooks/useChatRooms.ts
  src/pages/chat/hooks/useMessages.ts
  src/pages/chat/hooks/useUpdatePrice.ts
  src/pages/chat/types/chatRoom.ts
  src/pages/sell/hooks/usePatchSellApi.ts
  src/routes/router.tsx
  src/stores/AlertCountStore.ts
Labels: Feat, Refactor

#203 HotFix: 비로그인시 불필요한 api 호출 차단
  src/components/navBar/bottomNavBar/NavButton.tsx
  src/components/navBar/bottomNavBar/index.tsx
Labels: Fix

#207 Fix: 마이페이지, 구매페이지 7차 QA
  src/components/certification/index.tsx
  src/pages/purchase/reservationComplete.tsx
  src/styles/globalStyles.ts
Labels: Fix

#210 Fix: 알림, 홈, 숙소 상세 수정
  src/assets/2024_dragon.png
  src/components/numberBadge/index.tsx
  src/pages/home/components/Header/index.tsx
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/notice/index.tsx
  src/pages/notice/queries.ts
  src/pages/notice/styles.ts
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/products/api/queries.ts
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/ProductList/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/sell/stores/endDateStore.ts
  src/pages/speicialProducts/index.tsx
  src/pages/speicialProducts/styles.ts
  src/routes/router.tsx
Labels: Fix

#211 Fix: 2차 QA 반영
  src/components/card/ColumnCard/index.tsx
  src/components/card/RowCard/index.tsx
  src/components/loading/index.tsx
  src/pages/home/components/Banner/index.tsx
  src/pages/home/components/Banner/styles.ts
  src/pages/home/components/SpecialServices/index.tsx
  src/pages/productDetail/components/NegoButton/index.tsx
  src/pages/productDetail/index.tsx
  src/pages/products/components/ProductCard/index.tsx
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/components/SearchBar/index.tsx
  src/pages/products/index.tsx
  src/pages/search/components/BottomActions/index.tsx
  src/pages/search/components/SearchHistory/index.tsx
  src/pages/search/index.tsx
  src/utils/formatDateTo.ts
Labels: Fix

#215 Fix: 검색 히스토리 수정
  src/pages/search/components/SearchHistory/index.tsx
Labels: Fix

#216 Fix: 마이페이지, 구매페이지 8차 QA
  package.json
  src/pages/myPage/apis/getPurchaseHistory2.ts
  src/pages/myPage/hooks/usePurchaseHistory2.ts
  src/pages/myPage/hooks/usePurchaseTransactionHistory.ts
  src/pages/myPage/hooks/useSellTransactionHistory.ts
  src/pages/myPage/index.tsx
  src/pages/myPage/management.tsx
  src/pages/myPage/purchaseHistory.tsx
  src/pages/myPage/styles/terms.styles.ts
  src/pages/myPage/terms.tsx
  src/pages/myPage/transactionStatement.tsx
  src/pages/purchase/index.tsx
  src/pages/purchase/reservationComplete.tsx
  src/pages/term/styles.ts
  src/routes/router.tsx
  tsconfig.json
Labels: Fix, Feat

#217 [Fix & Design] 닉네임 중복 조회 API 에러 해결 & 로딩애니추가
  src/components/checkNickname/index.tsx
  src/components/checkPassword/index.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/login/EmailLogin.tsx
  src/pages/myPage/index.tsx
  src/pages/signIn/apis/compareNicknameApi.ts
Labels: Fix, Design

#219 Fix: 비로그인시 상세페이지 접근 오류 해결
  src/pages/productDetail/components/NegoButton/index.tsx
Labels: Fix

#223 Fix: 지도 현 위치 재검색 오류 수정
  src/pages/charge/list.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/home/components/Banner/images.ts
  src/pages/myPage/purchaseHistory.tsx
  src/pages/notice/index.tsx
  src/pages/products/api/queries.ts
  src/pages/products/components/KakaoMap/ProductsMarkers.tsx
  src/pages/products/components/KakaoMap/Research.tsx
  src/pages/products/components/KakaoMap/index.tsx
  src/pages/products/components/ProductCard/ProductCardForMap.tsx
  src/pages/products/components/ProductList/index.tsx
  src/pages/products/hooks/useIntersect.ts
  src/pages/products/index.tsx
Labels: Fix, Feat

#221 Feat: 홈 - 최근 본 상품
  src/components/card/RecentlyRowCard/index.tsx
  src/pages/home/components/RecentlyProduct/index.tsx
  src/pages/home/index.tsx
  src/pages/home/stores/recentStore.ts
  src/pages/home/types/recent.ts
  src/pages/products/components/ProductCard/index.tsx
Labels: Feat

#226 Fix: 비로그인 시 알림뱃지 숫자 제거 & 모달 버튼 색깔 변경
  src/components/modal/index.tsx
  src/pages/home/components/Header/index.tsx
  vite.config.ts
Labels: Fix

#230 Fix: 야놀자 결제 플로우 수정
  src/mocks/handlers.ts
  src/pages/charge/password.tsx
  src/pages/charge/pay.tsx
  src/pages/chat/components/chatText/index.tsx
  src/pages/productDetail/api/detail.ts
  src/pages/sell/components/NegoOption.tsx
  src/pages/sell/index.tsx
Labels: Fix

#229 Fix: 마이페이지, 구매페이지 9차 QA
  package.json
  src/pages/myPage/index.tsx
  src/pages/purchase/index.tsx
  src/pages/purchase/reservationComplete.tsx
Labels: Fix

#232 Fix: 존재하지 않는 회원 로그인 시 에러 처리
  src/pages/login/hooks/useLogin.ts
Labels: Fix

#227 Feat: 홈 알람 플로팅 버튼 생성 & 상세페이지 네고 버튼 수정
  package.json
  src/assets/lotties/approve.json
  src/components/card/RecentlyRowCard/index.tsx
  src/pages/home/index.tsx
  src/pages/home/styles/style.ts
  src/pages/notice/queries.ts
  src/pages/productDetail/components/Location/style.ts
  src/pages/productDetail/components/NegoButton/index.tsx
Labels: Feat

#235 Remove, Fix: 불필요 폴더 삭제 및 모바일 토스페이 결제시 에러 수정
  src/pages/home/hooks/useFCMToken.ts
  src/pages/myPage/accountTransfer.tsx
  src/pages/myPage/charge.tsx
  src/pages/myPage/points.tsx
  src/pages/myPage/serviceCenter.tsx
  src/pages/myPage/usageHistory.tsx
  src/pages/myPage/withdraw.tsx
  src/pages/purchase/editInfo.tsx
  src/pages/purchase/index.tsx
  src/pages/purchase/reservationComplete.tsx
  src/pages/purchase/styles/reservationComplete.style.ts
  src/pages/purchase/utils/onClickPayment.ts
  src/routes/router.tsx
Labels: Fix, Remove

#236 [Fix]: 채팅방 목록 가려지는 이슈 해결 및 Enter키 동작 추가
  src/pages/chat/components/chatInput/index.tsx
  src/pages/chat/styles/styles.ts
Labels: Fix, Feat

#238 Fix: 워딩 및 버튼삭제요청
  src/pages/charge/account.tsx
  src/pages/charge/success.tsx
  src/pages/sell/confirm.tsx
Labels: Fix
